"""Configuration values for the reproducible NPSDM release."""

INPUT_RELATIVE_PATH = "data/desired_setpoint_observations.csv"
OUTPUT_RELATIVE_PATH = "outputs/results"

EXPECTED_SUBJECTS = 62
OBSERVATIONS_PER_SUBJECT = 20
EXPECTED_OBSERVATIONS = EXPECTED_SUBJECTS * OBSERVATIONS_PER_SUBJECT
EXPECTED_MISSING_DESIRED = 117

GROUP_SIZES = tuple(range(3, 11))
REPETITIONS = 300
SMOKE_GROUP_SIZES = (3, 10)
SMOKE_REPETITIONS = 3
RANDOM_SEED = 20260904

SETPOINT_MIN_C = 12.0
SETPOINT_MAX_C = 33.0
SETPOINT_STEP_C = 0.1

UTILITY_WIDTH_C = 6.0
UTILITY_FLOOR = 1e-3
COVERAGE_BAND_C = 3.0
ATKINSON_EPSILONS = (0.0, 0.5, 1.0, 2.0, float("inf"))

PMV_CLO = 0.6
PMV_AIR_SPEED_M_S = 0.2
PMV_RELATIVE_HUMIDITY = 50.0
PMV_REFERENCE_MET = 1.1

RULES = ("pmv", "threshold_coverage", "mean", "median", "atkinson")
